[tool.poetry]
name = "django-cloud-provider-zones"
version = "0.1.13"
description = "Django app providing a static list of cloud provider regions and AZs"
authors = ["TJ <yolabingo@gmail.com>"]
readme = "README.md"
license = "src/django_cloud_provider_zones/LICENSE"
packages = [{include = "django_cloud_provider_zones", from = "src"}]
repository = "https://github.com/yolabingo/django-cloud-provider-zones"
keywords = ["django", "cloud", "provider", "regions", "aws", "gcp"]

[tool.poetry.dependencies]
python = ">=3.12"
django = "^6.0.2"
djangorestframework = "^3.16.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.15.4"
boto3 = "^1.42.59"
invoke = "^2.2.1"
pre-commit = "^4.5.1"
emoji = "^2.15.0"
tox = "^4.46.3"
django-extensions = "^4.1"
pyparsing = "^3.3.2"
pydot = "^4.0.1"
werkzeug = "^3.1.6"
rich = "^14.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
